





export type Post = {
  slug: string;
  title: string;
  date: string; // ISO format, e.g. "2026-03-01"
  topic: string; // e.g. "Writing", "Farm", "Life"
  excerpt: string;
  body: string[]; // one paragraph per array entry
};

// To add a post, copy the example below into the list, give it a unique
// slug, and fill in your own content. Posts are sorted newest-first
// automatically on the Musings page. For poems, use \n inside a
// paragraph for each line break; each paragraph is one stanza.
//
//  {
//    slug: "my-first-post",
//    title: "My first post",
//    date: "2026-10-01",
//    topic: "Writing",
//    excerpt: "A one-sentence teaser shown on the Musings page.",
//    body: [
//      "First paragraph.",
//      "Second paragraph.",
//    ],
//  },
export const posts: Post[] = [
  {
    slug: "grace-comes-first",
    title: "Grace Comes First",
    date: "2026-10-06",
    topic: "Faith",
    excerpt: "I believe in God for many of the same reasons other people don't.",
    body: [
      "I believe in God for many of the same reasons other people don't.",
      "Suffering. Disease. Natural disasters. War. Betrayal. Child abuse. Rape. Senseless death.",
      "How could there possibly be a God in light of all this? What kind of God would allow it?",
      "I understand the question. I have asked it myself. But I also find myself asking the opposite question: if there is no God, what are we supposed to do with all this suffering? What does any of it mean? Where do we take our grief when there is nothing beyond it?",
      "For me, the existence of suffering does not make God less believable. It makes the question of God more urgent.",
      "Organized religion has given people plenty of reasons to distrust it. Religion is run by human beings, and human beings are ambitious, tribal, inconsistent, power-seeking, and frequently wrong. Religion has been used to justify cruelty, exclusion, war, greed, and control.",
      "But for me, that is a separate question from whether God exists.",
      "Before asking whether Christianity, Islam, Judaism, Hinduism, or any other religion is true, I think there is a more basic question: is there something beyond us at all? Is there a creator? Is there a source behind existence?",
      "That was the question I spent years trying to answer.",
      "I read arguments for belief and against it. The cosmological argument, the design or fine-tuning argument, the moral argument, and even the more abstract ontological argument all gave me reasons to take belief seriously. None of them settled the question for me on its own, but taken together they made belief seem more reasonable to me than disbelief.",
      "The harder thing to dismiss was human experience. Across cultures and centuries, people have described moments of transcendence, conversion, answered prayer, overwhelming presence, or a sudden sense that reality is larger than what can be measured. I know those experiences can be interpreted in different ways, but I find it difficult to treat all of them as meaningless.",
      "Once I became convinced that God exists, Christianity became the next question.",
      "Again, I read everything I could.",
      "What struck me first was that something extraordinary clearly happened around Jesus of Nazareth. A small Jewish movement centered on a crucified teacher spread rapidly through the Roman world and survived persecution, internal conflict, and the deaths of its earliest leaders.",
      "The earliest Christians believed Jesus had risen from the dead, and they built their lives around that conviction. Some suffered and died rather than abandon it.",
      "People can die for beliefs that are false, so martyrdom by itself proves nothing. But it does tell me these early believers were not casually inventing a story they themselves knew to be a lie.",
      "Christianity also does not read to me like a legend that slowly emerged from some distant, unknowable past. The movement appeared quickly, centered on specific claims about a real person in a particular place and time. The earliest Christian writings come from the first generations of the movement, while people connected to the events were still alive.",
      "I was also struck by details that do not look like the easiest choices for someone inventing a persuasive story in that culture. The Gospel accounts place women prominently among the first witnesses to the empty tomb, even though women's testimony generally carried less social authority in the ancient world.",
      "None of this proves Christianity to me. But it makes it much harder for me to dismiss it as a fairy tale that gradually became religion.",
      "The part of Christianity that speaks most directly to the problem of suffering, though, is not a philosophical argument. It is the cross.",
      "Christianity does not describe a God who watches pain from a safe distance. It describes a God who enters it. Jesus experiences betrayal, humiliation, abandonment, physical agony, and death.",
      "That does not explain every tragedy or answer every question I have about suffering. But it changes the kind of God I am being asked to believe in.",
      "He is not untouched by what hurts us.",
      "There is another reason Christianity speaks to me, and it may be the most important one.",
      "Love sits at the center of it.",
      "Christianity does not merely command people to love. It makes the extraordinary claim that love is part of the very nature of God. \"God is love.\" The Christian understanding of the Trinity describes God as Father, Son, and Holy Spirit existing eternally in relationship. Love is not simply something God does. It is part of who Christians believe God is.",
      "That matters to me when I look at Jesus.",
      "Christians have not always been good at extending grace. We have a habit of sorting sins into categories, treating some as ordinary human weakness and others as reasons to keep people at a distance.",
      "I don't see much support for that instinct in Jesus.",
      "He repeatedly moves toward people respectable society would rather avoid: the poor, the sick, adulterers, tax collectors, prostitutes, people with damaged reputations, people who had already been judged.",
      "He does not always tell them that everything they have done is fine.",
      "But neither does He make moral perfection the admission price for coming near Him.",
      "That distinction means a great deal to me.",
      "Christianity does not tell me that God loves me once I become worthy of Him. It tells me that God loves me before I am worthy, while I am still capable of selfishness, lust, anger, dishonesty, pride, and every other way human beings hurt themselves and one another.",
      "Christianity does not begin with me climbing toward God.",
      "It begins with God coming toward me.",
      "And then there is my own life.",
      "I can look back and see many places where things could have gone badly, where my own choices could have carried me somewhere very different. Yet somehow I have been given more than I deserved.",
      "I don't experience that as evidence that God has made my life easy. He hasn't.",
      "I experience it more as a sense that He has not given up on me.",
      "There is something deeply comforting to me in believing that God knows every failure, every selfish decision, every wrong turn, and still wants something good for me. Grace, to me, feels a lot like being loved by someone who knows exactly who you are and stays anyway.",
      "There have also been moments when belief became something more than an argument.",
      "When my oldest son was baptized, I cried. I wasn't expecting to. I had watched him grow up, make his own choices, become his own person, and then I watched him publicly choose something that had become deeply important to me.",
      "For a few minutes, belief was not about cosmology or ancient manuscripts.",
      "It was my son standing in the water.",
      "I feel something related when I play music with the worship team at church. I know music can create emotion all by itself, and I don't confuse every strong feeling with proof of God. But there are moments when I am playing and singing with other people when I feel unusually connected: to them, to something beyond myself, and to the part of me that believes I was made for more than simply getting through another day.",
      "None of these things, by itself, proves God to me.",
      "Not the philosophical arguments.",
      "Not history.",
      "Not the cross.",
      "Not my son's baptism.",
      "Not the feeling I sometimes have while playing worship music.",
      "Not even the strange sense, looking back over my life, that I have been forgiven and carried farther than I deserved.",
      "It is the accumulation of them.",
      "They all seem to point in the same direction: toward a God who enters suffering, who moves toward broken people, who does not wait for us to clean ourselves up before loving us, and who does not give up on us when we fail.",
      "That is the God I find believable.",
      "Not because the world is free of suffering, but because it isn't.",
      "Not because human beings are particularly good, but because we aren't.",
      "Not because I have earned His attention, but because I haven't.",
      "Grace comes first.",
    ],
  },
  {
    slug: "intact-males",
    title: "Intact Males",
    date: "2026-10-06",
    topic: "Farm",
    excerpt: "Nature seems willing to tolerate an astonishing amount of male foolishness to keep the species going.",
    body: [
      "Nature seems willing to tolerate an astonishing amount of male foolishness to keep the species going.",
      "I know this, in part, because over about ten years I raised and bred a variety of farm animals: chickens, ducks, geese, turkeys, goats, cattle, pigs, and, for about a year, even a yak. After all that time, I reached one fairly simple conclusion.",
      "Females are much easier to live with.",
      "I make this observation with some reluctance, since I carry a Y chromosome myself.",
      "On the farm, that chromosome can produce some strange behavior.",
      "Roosters and ganders can become territorial enough to attack ankles, scratch legs, and terrorize children. My poor kids were afraid to leave the house at times. We had one orange rooster in particular who seemed to make it his daily mission to stalk them around the yard. Later we had a gander nearly as tall as they were, and, truthfully, I was a little afraid of him too.",
      "Drakes aren't especially intimidating to people, but they seem to spend nearly every waking hour relentlessly pursuing female ducks. It can become uncomfortable to watch.",
      "Then there are tom turkeys.",
      "Toms are probably my favorite male animals on the farm. They generally aren't frightening. They spend most of their time puffing themselves up, dragging their wings, fanning their tails, and strutting around as if the entire farm has assembled for the sole purpose of admiring them. They can also produce a deep drumming sound while they display.",
      "Watching a tom court a hen makes it difficult to believe that human males invented the sports car independently.",
      "As ridiculous as a tom can be, however, he still retains a certain dignity.",
      "The same cannot be said for a buck goat.",
      "A buck during breeding season is one of the strangest creatures I have ever encountered. He wears what can only be described as a shit-eating grin while chasing the does around the pasture. When he gets especially excited, he urinates on his own face, curls his upper lip, and appears deeply satisfied with himself.",
      "Apparently this is courtship.",
      "The does, meanwhile, are sweet and gentle. They smell like goats, which turns out to be perfectly pleasant until you meet a buck.",
      "A buck can be smelled from a remarkable distance. One can stink up an entire barn. They also become large, pushy, and sometimes aggressive. I have been chased around a pasture by one more than once.",
      "Life must be extremely committed to reproduction if this is one of the strategies it came up with.",
      "During COVID, apparently having exhausted all sensible hobbies, I bought a bull yak.",
      "We had Scottish Highland cattle at the time, and the idea was to breed the yak with our cows and produce some kind of interesting, lean meat animal.",
      "The yak had other plans.",
      "He seemed determined to make everyone miserable.",
      "One day my ten-year-old son walked into our fenced garden, which sat inside the same pasture. The yak was nowhere around when he went in. At some point afterward, the yak appeared and stationed himself directly outside the garden gate.",
      "My son couldn't get out.",
      "I didn't realize what had happened for nearly an hour. Eventually I noticed him stranded inside the garden and had to use a bucket of grain to lure the yak far enough away for him to escape.",
      "Another day my seventy-five-year-old neighbor called me.",
      "\"Your damn yak is in my yard and chasing me around. If I can get to my gun, it's going to be a dead yak.\"",
      "I hurried over and found my neighbor circling a large tree with the yak following him around it.",
      "Once again, grain saved the day.",
      "That was enough yak ownership for me.",
      "I called the woman I had bought him from and asked if she would take him back. She agreed. The yak evidently did not improve with age or relocation, because before long she had him processed into yak burger.",
      "That was not the last intact male bovine to complicate my life.",
      "A few years later I rented a Scottish Highland bull named Archie to breed our four cows.",
      "Archie was enormous, with the long hair and sweeping horns Highland cattle are known for, but he was also remarkably calm. For about three months he lived peacefully in our pasture. I fed him apples from behind the fence, scratched his big shaggy head, and eventually became comfortable enough to walk through the field while he was there.",
      "Then his owners brought back the trailer.",
      "Their plan was to leave it parked by the gate for a week so Archie could become accustomed to it before they came to take him home.",
      "Archie seemed to understand exactly what that trailer meant.",
      "Almost immediately, his behavior changed.",
      "He began snorting and pawing at the ground. One day I climbed over the fence to take care of something in the pasture. Archie stared at me and started scraping the dirt with his hoof.",
      "I decided it would be wise to leave.",
      "I was almost back to the fence when he charged.",
      "I had never seen an animal that large move that fast.",
      "Then again, I had never moved that fast either.",
      "I somehow managed to get over a five-foot fence before he reached me. Archie stopped on the other side, slammed his horns into the fence, and snorted.",
      "For the first time in three months, I had absolutely no doubt that Archie was a bull.",
      "His owners came the next day. When I told them what had happened, they figured Archie had become rather fond of our farm, particularly the four ladies living there, and had no intention of leaving.",
      "It took them most of the day to get him into the trailer. Grain wasn't enough. Eventually they resorted to a compressed-air horn to frighten him forward.",
      "Once inside the trailer, he settled down again.",
      "I spoke with his owners about a month later. They told me Archie had never returned to being the sweet, gentle giant he had once been.",
      "He was, however, now living comfortably in several freezers as hamburger.",
      "Farmers figured out a long time ago that intact males come with certain complications.",
      "With cattle, goats, and yaks, one common solution is banding. A heavy rubber band is placed around the testicles, cutting off the blood supply until they eventually atrophy and fall away.",
      "At least none of the animals ever complained to me about it.",
      "Pigs are another matter. Castrating piglets is considerably more hands-on, and after participating in it, I can confidently say it is not an experience I need to repeat. The piglet screams as if being murdered, which, from his perspective, may not be an unreasonable interpretation of events.",
      "Then you set him back down and, within moments, he usually wanders away and resumes ordinary pig business as if nothing happened.",
      "I like to believe some of the screaming was theatrical.",
      "For the record, I am recommending castration only for farm animals.",
      "Still, after enough years around intact males, certain patterns become difficult to ignore.",
      "The tom wants to be seen.",
      "The rooster and the gander want territory.",
      "The drake won't take a hint.",
      "The buck abandons all dignity.",
      "The bull refuses to give up what he thinks is his.",
      "It would be comforting to believe all of this behavior belongs safely on the other side of the fence.",
      "Unfortunately, I am male too.",
      "I have never urinated on my own face in an attempt to attract a woman, which feels worth mentioning.",
      "But I did once wear cheap cologne to a school dance. During a slow dance, I was fairly sure I was winning the girl over. Then she said, \"Your cologne is so strong I can barely breathe.\"",
      "That brought me down to size in a hurry.",
      "In my own mind, I had smelled irresistible. I imagine the buck feels the same way.",
      "I have bought nice clothes and flowers and worried far too much about how I looked. I have driven cars that probably said more about what I wanted people to think of me than I would have admitted at the time. I have stared into a mirror over a pimple as if my entire romantic future depended on it.",
      "I've competed with other men when there was nothing meaningful to win and defended territory that existed mostly in my own head. More than once, I've acted differently simply because a woman I found attractive was nearby. Mostly, I have tried to look more impressive than I felt.",
      "The methods may be more refined, but the underlying impulses don't always feel that different.",
      "A tom turkey may look ridiculous, but at least he is honest about what he's doing.",
      "The longer I lived around all those animals, the more impressed I became with the females. The hens, does, cows, and sows somehow endured the strutting, chasing, fighting, smelling, and general nonsense and still managed to keep the species going.",
      "Across species, females seem remarkably patient with the males nature has assigned them.",
      "As a male, I feel a certain gratitude on behalf of my half of creation.",
      "Maybe the real difference between us and the animals isn't that we escaped those impulses. Maybe it is that we can recognize them, laugh at ourselves, and occasionally decide not to obey them.",
      "The animals don't have that luxury.",
      "And judging by how many of the intact males on my farm eventually ended up in the freezer, perhaps that's worth remembering.",
    ],
  },
  {
    slug: "what-the-touch-is-saying",
    title: "What the Touch Is Saying",
    date: "2026-10-02",
    topic: "Life",
    excerpt: "The touch feels good, but what matters more to me is what the touch is saying.",
    body: [
      "I really desire physical affection. I like hugging, snuggling, spooning, resting my head against someone's shoulder, and feeling someone rest her head against mine.",
      "Some time ago, something caused me to question that desire in a way I never had before. I was confronted with the possibility that my desire for physical closeness might come from some unmet childhood need—that perhaps I was trying to reclaim something I hadn't received as a child.",
      "The idea hurt more than I expected it to.",
      "Maybe because something I had always considered tender and ordinary suddenly felt like evidence that something was wrong with me. Physical affection had always felt adult and mutual to me—two people expressing love, trust, desire, or simply the wish to be close. Seeing that same desire as a child in me reaching for something he had never received made me question something about myself I had never thought needed questioning.",
      "Or maybe because there was enough truth in it to make me wonder.",
      "I had, after all, lost my mother when I was three years old.",
      "It was probably the most consequential event of my life, even though I was too young to understand what had happened. Her death sent my life down a road completely different from the one I would have traveled had she lived. What that other road might have looked like is impossible to know.",
      "It seems likely that I have some unmet childhood needs.",
      "But who doesn't?",
      "Maybe yours came from a parent who wasn't affectionate. Maybe you were bullied, overlooked, abandoned, criticized too much or praised too little. Maybe you grew up surrounded by love and still came away needing something you didn't get. Childhood isn't something any of us emerges from with every need perfectly met.",
      "And more importantly, how could we ever know definitively what is an unmet childhood need and what is simply a normal adult need?",
      "I can understand why viewing physical affection through the lens of an unmet childhood need might make it feel different. It could begin to seem parental rather than romantic. Holding someone might no longer look like two adults seeking closeness, but like one adult being asked to comfort the child still living somewhere inside the other. I can understand why that distinction might matter.",
      "But that's not how I experience it. When I put my head on someone's shoulder, I don't feel like a three-year-old looking for his mother. I feel like a grown man who loves being close to another human being.",
      "And yet maybe that distinction is too easy. Maybe some small part of that three-year-old is there when I put my head on someone's shoulder. I don't know. That's the problem with trying to draw a line between the child we were and the adult we became. I'm not sure there is one.",
      "The more I've thought about it, the less certain I am that the distinction even matters.",
      "Of course, where our needs come from can matter. Childhood wounds can follow us into adulthood in ways that hurt us and the people around us, and those are worth understanding. But wanting something because you once lacked it doesn't automatically make the wanting unhealthy.",
      "I can't completely separate the child from the adult in me, nor am I sure I should try. The three-year-old who lost his mother didn't disappear when I turned eighteen. He grew up. His loss grew up with him. It became part of me, along with everything else that happened in the years that followed.",
      "Maybe some of my desire for affection began there. Maybe all of it did. Maybe none of it did. I'll never know.",
      "We all carry our childhoods with us. They shape what frightens us, what comforts us, what makes us feel safe, and probably the ways we give and receive love. If I enjoy resting my head against someone's shoulder, does it matter whether some psychologist could trace that desire back fifty years? Would knowing its origin make the comfort I feel today any less real?",
      "I don't think so.",
      "There is something wonderfully simple about physical affection. A hand resting on your back. Someone leaning against you on the couch. A long hug from someone who doesn't seem anxious to let go. Falling asleep with another person pressed against you.",
      "And I like both sides of it. I love resting my head against someone's shoulder, but I love feeling someone rest her head against me just as much. There is something deeply satisfying about that small gesture of vulnerability. It feels like trust. Like she feels safe with me. Like, for that moment, I am someone she can let her guard down with.",
      "I've also come to realize that maybe the physical sensation isn't even what I desire most.",
      "It's the intention behind it.",
      "A hand reaches for mine because someone wants to hold it. A head settles onto my shoulder because that's where someone wants to be. An embrace lasts a few seconds longer because neither person is quite ready to let go.",
      "The touch feels good, but what matters more to me is what the touch is saying.",
      "I want to be close to you.",
      "Maybe that's what I've been looking for all along.",
      "All I know is that if I lacked affection and closeness as a child, I sure the hell am going to try to find it as an adult.",
      "I want to hug someone I love. I want to spoon on the couch. I want to rest my head against someone's shoulder and have someone rest hers against mine. I want that special connectedness that doesn't need to be explained or diagnosed. I don't need to know which part of me is asking for it.",
      "Sometimes a person just wants to be held.",
    ],
  },
  {
    slug: "bear-witness",
    title: "Bear Witness",
    date: "2026-09-26",
    topic: "Life",
    excerpt: "Maybe when an old person repeats a story, they are asking us to help them remember that their life happened.",
    body: [
      "I recently read about a man in his mid-nineties who had lived a remarkable life, the kind of life most people only see in movies. What stayed with me wasn't anything he had accomplished. It was something small. He said he could tell when his grandchildren were only being polite while he talked to them, that they had no real curiosity about what he had to say. If that can be true for someone whose stories strangers would line up to hear, what must it be like for everyone else?",
      "Imagine reaching an age when almost everyone who remembers the younger version of you is gone. The people who knew what your mother's voice sounded like. The friend who remembers what happened that summer when you were sixteen. The person who was standing beside you when you met your wife. The brother who knew the family jokes without having them explained. One by one, the witnesses disappear, until you may be the only person alive who remembers entire rooms of your own life.",
      "That can be the reality for anyone who lives deep into their nineties. It may take all their concentration to cross a room. Their eyes may hurt in ordinary light. Things the young barely notice, like a meal, a night's sleep, or a trip to the bathroom, become the measures of a good day. But the hardest part is not the body. It is being left behind.",
      "Many people as they grow old talk about the past, and some tell the same stories again and again. Maybe when they repeat a story, they aren't simply trying to tell us something. Maybe they are asking us to help them remember that their life happened. The stories come from a time when they had fire in their hearts, when people depended on them, when they fell in love and raised children and earned a living and made mistakes. It was a time when most of life still seemed to be happening in front of them instead of behind them. That is how life feels to most of us when we are younger, and we barely notice how temporary that privilege is.",
      "I wonder if part of the reason we sometimes hesitate to spend time with the very old is that they remind us of our own mortality and of everyone we love. Maybe that is the gift they are offering, if we would only listen: an awareness of how fragile and brief all of this is.",
      "I don't know what to do with that reality without God. I have tried to imagine a universe in which everyone I have ever loved simply disappears and everything we built turns to dust. I find no comfort there. Faith is the only answer I have found that lets me look directly at death without concluding that everything before it was meaningless.",
      "So the next time an old man tells me a story I've already heard, I hope I can resist the urge to hurry him along. Maybe he isn't repeating himself because he forgot he told me. Maybe he simply needs to visit that place again. And perhaps, by listening, I can go there with him.",
      "There might come a day when my own world exists mostly in memory. I hope someone will sit still long enough to let me tell them about it.",
    ],
  },
  {
    slug: "curtains",
    title: "Curtains",
    date: "2026-09-25",
    topic: "Poetry",
    excerpt: "I heard a whisper pass.",
    body: [
      "I heard a whisper pass.\nBreathless.\nIt held me fast.\nFrozen.",
      "Across the ceiling a shadow bloomed.\nMoonlight drained from the room.\nTen thousand shards of silence.\nA quiet\nviolence.",
      "The curtain folds fall still.\nI never will.",
    ],
  },
];
